name: Check
on:
  pull_request:
  push:
    branches: main

jobs:
  check:
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@master
          with:
            toolchain: "stable"
        - uses: taiki-e/install-action@cargo-hack
        - uses: Swatinem/rust-cache@v2
        - run: cargo hack check --feature-powerset
  
  test:
    runs-on: "ubuntu-latest"
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - run: cargo hack test --feature-powerset